# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Tabulate Value Matrix R
#'
#' Construct a subject (row) by evluation time (col) matrix.
#'  
#' @param eval_times Evaluation times.
#' @param idx Unique subject index. 
#' @param time Observation time.
#' @param value Observation value.
#' @return Numeric matrix.
#' @export
ValueMatrixR <- function(eval_times, idx, time, value) {
    .Call(`_AURMC_ValueMatrixR`, eval_times, idx, time, value)
}

#' Tabulate Kaplan Meier R
#'
#' Constructs a matrix with evaluation times as rows, and 3 columns, for 
#' time, number at risk, and Kaplan-Meier survival probability.
#'  
#' @param eval_times Evaluation times.
#' @param idx Unique subject index.
#' @param status Status, 0 for censoring, 1 for event, 2 for death.
#' @param time Observation time.
#' @return Data.frame.
KaplanMeierR <- function(eval_times, idx, status, time) {
    .Call(`_AURMC_KaplanMeierR`, eval_times, idx, status, time)
}

#' Tabulate Estimator R
#'  
#' @param idx Unique subject index. 
#' @param status Status, coded as 0 for censoring, 1 for event. 
#' @param time Observation time.
#' @param value Observation value.
#' @param eval_times Evalulation times. If omitted, defaults to the
#' unique values of time.
#' @param replace_na Replace NaN with zero? Default: FALSE.
#' @param return_auc Return the AUC? Default: FALSE.
#' @param trunc_time Truncation time? Optional. If omitted, defaults
#' to the maximum evaluation time.
#' @return Data.frame.
#' @export 
EstimatorR <- function(idx, status, time, value, eval_times = NULL, replace_na = FALSE, return_auc = FALSE, trunc_time = NULL) {
    .Call(`_AURMC_EstimatorR`, idx, status, time, value, eval_times, replace_na, return_auc, trunc_time)
}

#' Draw Bootstrap R
#'  
#' @param idx Unique subject index. 
#' @param status Status, coded as 0 for censoring, 1 for event. 
#' @param time Observation time.
#' @param value Observation value.
#' @return Numeric matrix.
DrawBootstrapR <- function(idx, status, time, value) {
    .Call(`_AURMC_DrawBootstrapR`, idx, status, time, value)
}

#' Bootstrap Samples R
#'
#' Returns a bootstrap (row) by statistic (col) matrix. If \code{return_auc = TRUE},
#' the output has a single column, the AUC. If \code{return_auc = FALSE}, the output
#' has a single column for each evaluation time.
#'  
#' @param boot Bootstrap replicates.
#' @param eval_times Evaluation times.
#' @param idx Unique subject index. 
#' @param status Status, coded as 0 for censoring, 1 for event. 
#' @param time Observation time.
#' @param value Observation value.
#' @param replace_na Replace NaN with zero?
#' @param return_auc Return the AUC?
#' @param trunc_time Truncation time? Optional. If omitted, defaults
#' to the maximum evaluation time.
#' @return Numeric matrix.
#' @export
BootstrapSamplesR <- function(boot, eval_times, idx, status, time, value, replace_na = FALSE, return_auc = FALSE, trunc_time = NULL) {
    .Call(`_AURMC_BootstrapSamplesR`, boot, eval_times, idx, status, time, value, replace_na, return_auc, trunc_time)
}

#' Calculate Mu R
#'
#' Evaluate \eqn{\mu(t; \tau) = \int_{t}^{\tau}{S(u)d(u)/y(u)}du}.
#' 
#' @param d Value of d(t) at each time point.
#' @param surv Value of S(t) at each time point.
#' @param time Values of time t.
#' @param y Value of y(t) at each time point.
#' @return Numeric vector of \eqn{\mu(t; tau)}.
CalcMuR <- function(d, surv, time, y) {
    .Call(`_AURMC_CalcMuR`, d, surv, time, y)
}

#' Calculate Martingale
#'
#' Calculate \eqn{dM_{i}(t) = dN_{i}(t) - Y_{i}(t)d\Lambda(t)}.
#' 
#' @param haz Value of the hazard at each unique time.
#' @param idx Subject index.
#' @param status Subject status.
#' @param time Subject observation times.
#' @param unique_times Unique times at which to obtain the martingale.
#' @return Matrix with subjects as rows and unique times as columns.
CalcMartingaleR <- function(haz, idx, status, time, unique_times) {
    .Call(`_AURMC_CalcMartingaleR`, haz, idx, status, time, unique_times)
}

CalcMartingaleCpp <- function(haz, idx, status, time, unique_times) {
    .Call(`_AURMC_CalcMartingaleCpp`, haz, idx, status, time, unique_times)
}

CalcI1Cpp <- function(dm, mu, y) {
    .Call(`_AURMC_CalcI1Cpp`, dm, mu, y)
}

#' Influence Function R
#' 
#' Influence function contributions for the AUC.
#'  
#' @param idx Unique subject index. 
#' @param status Status, coded as 0 for censoring, 1 for event. 
#' @param time Observation time.
#' @param trunc_time Truncation time? Optional. If omitted, defaults
#' to the maximum evaluation time.
#' @param value Observation value.
#' @return Data.frame.
#' @export 
InfluenceR <- function(idx, status, time, trunc_time, value) {
    .Call(`_AURMC_InfluenceR`, idx, status, time, trunc_time, value)
}

