# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Tabulate Value Matrix R
#'
#' Construct a subject (row) by unique time (col) matrix.
#'  
#' @param eval_times Evaluation times.
#' @param idx Unique subject index. 
#' @param status Status, 0 for censoring, 1 for event, 2 for death.
#' @param time Observation time.
#' @param value Observation value.
#' @return Numeric matrix.
#' @export
ValueMatrixR <- function(eval_times, idx, status, time, value) {
    .Call(`_AURMC_ValueMatrixR`, eval_times, idx, status, time, value)
}

#' Tabulate Kaplan Meier R
#'
#' Constructs a matrix with evaluation times as rows, and 3 columns, for 
#' time, number at risk, and Kaplan-Meier survival probability.
#'  
#' @param eval_times Evaluation times.
#' @param idx Unique subject index.
#' @param status Status, 0 for censoring, 1 for event, 2 for death.
#' @param time Observation time.
#' @return Data.frame.
KaplanMeierR <- function(eval_times, idx, status, time) {
    .Call(`_AURMC_KaplanMeierR`, eval_times, idx, status, time)
}

#' Tabulate Estimator R
#'  
#' @param idx Unique subject index. 
#' @param status Status, coded as 0 for censoring, 1 for event. 
#' @param time Observation time.
#' @param value Observation value.
#' @param eval_times Times at which to evaluate the estimator.
#' @param replace_na Replace NaN with zero?
#' @param return_auc Return the AUC?
#' @return Data.frame.
#' @export 
EstimatorR <- function(idx, status, time, value, eval_times = NULL, replace_na = FALSE, return_auc = FALSE) {
    .Call(`_AURMC_EstimatorR`, idx, status, time, value, eval_times, replace_na, return_auc)
}

#' Draw Bootstrap R
#'  
#' @param idx Unique subject index. 
#' @param status Status, coded as 0 for censoring, 1 for event. 
#' @param time Observation time.
#' @param value Observation value.
#' @return Numeric matrix.
DrawBootstrapR <- function(idx, status, time, value) {
    .Call(`_AURMC_DrawBootstrapR`, idx, status, time, value)
}

#' Bootstrap Samples R
#'  
#' @param boot Bootstrap replicates.
#' @param eval_times Evaluation times.
#' @param idx Unique subject index. 
#' @param status Status, coded as 0 for censoring, 1 for event. 
#' @param time Observation time.
#' @param value Observation value.
#' @param return_auc Return the AUC?
#' @return Numeric matrix.
#' @export
BootstrapSamplesR <- function(boot, eval_times, idx, status, time, value, return_auc = FALSE) {
    .Call(`_AURMC_BootstrapSamplesR`, boot, eval_times, idx, status, time, value, return_auc)
}

